### ISSUE TITLE
Get geocoding just by zip

### ISSUE THREAD

**Issue by mahdsip** [cjgb/caRtociudad#1]
Hello,
This library is really helpfull, it would be even more if you could just retrieve the centroide based just on the zip code. ¿Is there any plannification for adding such new features?

Thanks

**Comment by cjgb** [comment]
Short answer, no.

Long answer: caRtociudad is a light wrapper for cartociudad.es API. Requests are forwarded upstream. We cannot do anything cartociudad does not support.
