### ISSUE TITLE
Adapt some endpoints to newer versions

### ISSUE THREAD

**Issue by koldLight** [cjgb/caRtociudad#2]
cartociudad has improved some of their services, by adding new endpoints for doing:

* geocoding
* reverse geocofing

More details [here](http://blog-idee.blogspot.com.es/2017/02/nuevo-geocodificador-de-cartociudad.html)

Their [API reference doc](http://www.cartociudad.es/recursos/Documentacion_tecnica/CARTOCIUDAD_ServiciosWeb.pdf) will be update soon

**Comment by carlosvergara** [comment]
I have adapted some functions to this end. Check this PR (#4).

**Comment by koldLight** [comment]
Wow, that's perfect! I'll take a look to the PR

**Comment by koldLight** [comment]
Resolved by @carlosvergara in PR #4
